spring:
  cloud:
    gateway:
      routes:
        # product
        - id: product_route
          uri: lb://mall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        # member
        - id: member_route
          uri: lb://mall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        # ware
        - id: ware_route
          uri: lb://mall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        # coupon
        - id: coupon_route
          uri: lb://mall-coupon
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        # secKill
        - id: coupon_route
          uri: lb://mall-seckill
          predicates:
            - Path=/api/seckill/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        # third
        - id: third_route
          uri: lb://mall-third
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty(?<segment>.*),/$\{segment}
        # admin
        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}
        # host
        - id: host_route
          uri: lb://mall-product
          predicates:
            - Host=gulimall.com,item.gulimall.com,192.168.31.79
        # search-host
        - id: search_host_route
          uri: lb://mall-search
          predicates:
            - Host=search.gulimall.com
        # auth
        - id: auth_route
          uri: lb://mall-auth
          predicates:
            - Host=auth.gulimall.com
        # cart
        - id: cart_route
          uri: lb://mall-cart
          predicates:
            - Host=cart.gulimall.com
        # order
        - id: order_route
          uri: lb://mall-order
          predicates:
            - Host=order.gulimall.com
        # member
        - id: member_route
          uri: lb://mall-member
          predicates:
            - Host=member.gulimall.com
        # icu
        - id: icu_route
          uri: https://996.icu/#/zh_CN
          predicates:
            - Path=/icu
          filters:
            - RedirectTo=302,https://996.icu/#/zh_CN

  redis:
    host: redis-server
    password: lb82ndLF
    port: 6379
    database: 0

config:
  version: v0.1