spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://scorpio-study.mysql.cn-chengdu.rds.aliyuncs.com/mall-pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: dbadmin
    password: lb82ndLF

  redis:
    host: redis-server
    password: lb82ndLF
    port: 6379
    database: 0

  rabbitmq:
    host: rabbitmq-server
    virtual-host: /
    username: mqAdmin
    password: lb82ndLF@mq
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual

  cache:
    type: redis
    redis:
      time-to-live: 3600000

  session:
    store-type: redis
    timeout: 6000000

  thymeleaf:
    cache: false

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

seata:
  application-id: ${spring.application.name}
  registry:
    type: nacos
    nacos:
      application: mall-seata
      server-addr: ${spring.cloud.nacos.discovery.server-addr}
      group : SEATA_GROUP
      namespace: 4e3012ce-93ab-49cb-8ad3-e93a3860b268
      username: nacos
      password: lb82ndLF
  tx-service-group: default_tx_group
  service:
    vgroup-mapping:
      default_tx_group: default

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  # 主键生成规则
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl

logging:
  level:
    com.study.mall: debug

thread:
  core-size: 20
  max-size: 200
  keep-alive: 10

config:
  version: v0.1