spring:
  redis:
    host: redis-server
    password: lb82ndLF
    port: 6379
    database: 0
    timeout: 500
    testOnBorrow: true
    testWhileIdle: true
    testOnReturn: true

  rabbitmq:
    host: rabbitmq-server
    virtual-host: /
    username: mqAdmin
    password: lb82ndLF@mq
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual

  task:
    execution:
      pool:
        core-size: 5
        max-size: 50

  thymeleaf:
    cache: false

management:
  endpoints:
    web:
      exposure:
        include: '*'

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  # 主键生成规则
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl

thread:
  core-size: 20
  max-size: 200
  keep-alive: 10

config:
  version: v0.1