spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://scorpio-study.mysql.cn-chengdu.rds.aliyuncs.com/mall-wms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: dbadmin
    password: lb82ndLF

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  redis:
    host: redis-server
    password: lb82ndLF
    port: 6379
    database: 0
    timeout: 500
    testOnBorrow: true
    testWhileIdle: true
    testOnReturn: true

  rabbitmq:
    host: rabbitmq-server
    virtual-host: /
    username: mqAdmin
    password: lb82ndLF@mq
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual

seata:
  application-id: ${spring.application.name}
  registry:
    type: nacos
    nacos:
      application: mall-seata
      server-addr: ${spring.cloud.nacos.discovery.server-addr}
      group : SEATA_GROUP
      namespace: 4e3012ce-93ab-49cb-8ad3-e93a3860b268
      username: nacos
      password: lb82ndLF
  tx-service-group: default_tx_group
  service:
    vgroup-mapping:
      default_tx_group: default

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  # 主键生成规则
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl

logging:
  level:
    com.study.mall: debug

config:
  version: v0.1