spring:
  redis:
    host: redis-server
    password: lb82ndLF
    port: 6379
    database: 0
    timeout: 500
    testOnBorrow: true
    testWhileIdle: true
    testOnReturn: true

  thymeleaf:
    cache: false

  zipkin:
    base-url: http://zipkin-server:9411
    discovery-client-enabled: false
    sender:
      type: web
    sampler:
      probability: 1.0

logging:
  level:
    com.study.mall: debug

management:
  endpoints:
    web:
      exposure:
        include: '*'

config:
  version: v0.1