spring:
  cloud:
    alicloud:
      access-key: LTAI5tL9d9WnRqMhDV17wjs3
      secret-key: WR1rvBso2Ci0fdD6tkT2y6riTc1VoF
      oss:
        endpoint: oss-cn-chengdu.aliyuncs.com
        bucket: mall-zero-copy
        host: https://${spring.cloud.alicloud.oss.bucket}.${spring.cloud.alicloud.oss.endpoint}

  redis:
    host: redis-server
    password: lb82ndLF
    port: 6379
    database: 0
    timeout: 500
    testOnBorrow: true
    testWhileIdle: true
    testOnReturn: true